-----------------------------------------------------------
-- Author:      Jim Lynch
-- Date:        10/20/2021
-- Description: Updates a service order by ID
-----------------------------------------------------------

CREATE PROCEDURE  [dbo].[spServiceOrders_UpdateByID]
	@ID int OUTPUT,
	@FSR varchar(50), 
	@ServiceOrderNumber int, 
	@SignalNumber varchar(50), 
	@RouteNumber int ,
    @Cycle int,
	@Rate varchar(50), 
	@MeterNumber int,
	@LocationNumber varchar(50),
	@AccountNumber int,
    @SubAccountNumber int,
	@ServiceNumber int,
    @AccountName varchar(100),
    @AccountAddress1 varchar(100),
    @AccountAddress2 varchar(100),
    @AccountAddress3 varchar(100),
    @AccountZip varchar(20),
	@Address varchar(100),
    @AddressStreetNumber int,
    @CutoffCreatorUserID varchar(50),
	@ExistingDeposit money,
	@AdditionalDeposit money,
    @TotalDeposit money,
    @GuarantorAccountNumber int,
    @GuarantorSubAccountNumber int,
    @GuarantorAmount money,
	@AddedCharges money,
	@LetterPrinted bit,
    @ServiceOrderDate datetime2(7),
	@Completed bit,
	@DateCompleted datetime2(7),
    @Archived bit,
    @DateArchived datetime2(7),
    @Reading int,
    @SignalChange varchar(255),
	@PaymentReceived bit,
    @KeyAccountString varchar(10),
    @OnlinePayment bit,
    @BankDraft bit
AS
    BEGIN
      UPDATE ServiceOrders
      SET	FSR = @FSR,
	        ServiceOrderNumber = @ServiceOrderNumber,
            SignalNumber = @SignalNumber,
            RouteNumber = @RouteNumber,
            Cycle = @Cycle,
            Rate = @Rate,
            MeterNumber = @MeterNumber, 
            LocationNumber = @LocationNumber,
            AccountNumber = @AccountNumber,
            SubAccountNumber = @SubAccountNumber,
            ServiceNumber = @ServiceNumber,
            AccountName = @AccountName,
            AccountAddress1 = @AccountAddress1,
            AccountAddress2 = @AccountAddress2,
            AccountAddress3 = @AccountAddress3,
            AccountZip = @AccountZip,
            Address = @Address,
            AddressStreetNumber = @AddressStreetNumber,
            CutoffCreatorUserID = @CutoffCreatorUserID,
            ExistingDeposit = @ExistingDeposit,
            AdditionalDeposit = @AdditionalDeposit,
            TotalDeposit = @TotalDeposit,
            GuarantorAccountNumber = @GuarantorAccountNumber,
            GuarantorSubAccountNumber = @GuarantorSubAccountNumber,
            GuarantorAmount = @GuarantorAmount,
            AddedCharges = @AddedCharges,
            LetterPrinted = @LetterPrinted,
            ServiceOrderDate = @ServiceOrderDate,
            Completed = @Completed,
            DateCompleted = @DateCompleted,
            Archived = @Archived,
            DateArchived = @DateArchived,
            Reading = @Reading,
            SignalChange = @SignalChange,
            PaymentReceived = @PaymentReceived,
            KeyAccountString = @KeyAccountString,
            OnlinePayment = @OnlinePayment,
            BankDraft = @BankDraft
      WHERE [ID] = @ID
    END