CREATE TABLE [dbo].[UserSettings](
	[UserID] [varchar](50) NOT NULL,
	[Role] [varchar](50) NOT NULL,
	[FirstName] [varchar](50) NULL,
	[LastName] [varchar](50) NULL,
	[Filter] [varchar](50) NULL,
    [FontSize] [int] NULL,
	[ShowColumnSONumber] [bit] NULL,
	[ShowColumnSignalNumber] [bit] NULL,
	[ShowColumnFSR] [bit] NULL,
	[ShowColumnMeterNumber] [bit] NULL,
	[ShowColumnReading] [bit] NULL,
	[ShowColumnRate] [bit] NULL,
	[ShowColumnRouteNumber] [bit] NULL,
	[ShowColumnLocationNumber] [bit] NULL,
	[ShowColumnAddress] [bit] NULL,
	[ShowColumnAccountNumber] [bit] NULL,
	[ShowColumnExistingDeposit] [bit] NULL,
	[ShowColumnAdditionalDeposit] [bit] NULL,
	[ShowColumnAddedCharges] [bit] NULL,
	[ShowColumnSignalChange] [bit] NULL,
	[ShowColumnLetterPrinted] [bit] NULL,
    [SortColumn] [varchar] (50) NULL,
    [SortAscending] [bit] NULL,
	[RefreshInterval] [int] NULL,
	[EmailAddress] [varchar](100) NULL,
	[ColorCoding] [bit] NULL, 
    [ThemeSyncMode] [varchar] (50) NULL,
    [AppTheme] [varchar] (50) NULL,
    [AccentColor] [varchar] (50) NULL,
    [KeyAccountColor] [varchar] (50) NULL,
    [CompletedColor] [varchar] (50) NULL,
    [GoodSignalColor] [varchar] (50) NULL,
    [PaymentReceivedColor] [varchar] (50) NULL,
    [OnlinePaymentColor] [varchar] (50) NULL,
    [BankDraftColor] [varchar] (50) NULL,
    CONSTRAINT [PK_UserSettings] PRIMARY KEY ([UserID])
) ON [PRIMARY]